# Generated by Django 6.0.4 on 2026-05-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_amenityvaluation_id_alter_finalvaluation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyidentification',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='propertyidentification',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
