# Generated by Django 6.0.4 on 2026-05-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_propertyidentification_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyidentification',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='propertyidentification',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='propertyidentification',
            name='approved_usage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='propertyidentification',
            name='approving_authority',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
