# Generated by Django 4.2.30 on 2026-05-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_remove_propertyidentification_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyphoto',
            name='bearing_degrees',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='propertyphoto',
            name='bearing_direction',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='propertyphoto',
            name='captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyphoto',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='propertyphoto',
            name='locality',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='propertyphoto',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='propertyphoto',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
