export const initialFormData = {
  institutionDetails: {
    bank_name: '',
    branch_name: '',
    vendor_engineer_institution_name: '',
    vendor_contact_number: '',
    site_engineer_name: '',
    site_engineer_contact_number: '',
    loan_application_id: '',
    product_loan_type: '',
    applicant_name: '',
    applicant_contact_number: '',
    property_owner_name: '',
    property_owner_contact_number: '',
    person_met_at_site: '',
    person_met_contact_number: '',
    relationship_with_applicant: '',
    property_holding_type: 'freehold',
    property_type: 'vacant_land',
    other_property_type: '',
    property_sub_type: '',
    date_of_inspection: '',
    date_of_report: '',
    document_number: '',
    execution_date: '',
    expiry_date: '',
    in_favour_of: '',
    approval_authority: '',
  },
  verifiedDocuments: [
    {
      type_of_document: '',
      document_number: '',
      execution_date: '',
      expiry_date: '',
      in_favour_of: '',
      approval_authority: '',
    },
  ],
  propertyIdentification: {
    address_as_per_documents: '',
    address_as_per_actual_site: '',
    address_as_per_plan: '',
    survey_number: '',
    plot_no_flat_no: '',
    lpm_approval_no: '',
    door_no: '',
    assessment_no: '',
    landmark: '',
    locality_name: '',
    grama_polam: '',
    jurisdiction: '',
    taluka: '',
    mandal: '',
    district: '',
    state: '',
    pincode: '',
    layout_plan_available: true,
    construction_plan_available: true,
    plan_validity: true,
    approving_authority: '',
    approved_usage: '',
  },
  scheduleDetails: {
    east_boundary_docs: '',
    west_boundary_docs: '',
    north_boundary_docs: '',
    south_boundary_docs: '',
    east_boundary_actual: '',
    west_boundary_actual: '',
    north_boundary_actual: '',
    south_boundary_actual: '',
    east_boundary_plan: '',
    west_boundary_plan: '',
    north_boundary_plan: '',
    south_boundary_plan: '',
    east_boundary_status: '',
    west_boundary_status: '',
    north_boundary_status: '',
    south_boundary_status: '',
    docs_title: '',
    actual_title: '',
    plan_title: '',
    extra_boundaries: { docs: [], actual: [], plan: [] },
    property_identification_status: '',
    construction_type: '',
    other_construction_type: '',
    roof_type: '',
    other_roof_type: '',
    flooring_type: '',
    other_flooring_type: '',
    stair_type: '',
    other_stair_type: '',
    no_of_floors_approved: '',
    no_of_floors_existing: '',
    construction_quality: '',
    maintenance_of_property: '',
    occupancy_status: '',
    occupant_details: '',
    actual_usage_of_property: '',
    approved_usage_of_property: '',
    class_of_locality: '',
    other_class_of_locality: '',
    number_of_floors: '',
  },
  infrastructureDetails: {
    land_locked: true,
    land_locked_description: '',
    number_of_roads: '',
    road_direction: '',
    approach_road_type: '',
    other_approach_road_type: '',
    type_of_access: '',
    road_width_ft: '',
    electricity: true,
    water: true,
    drainage_connection: true,
    number_of_lifts: '',
  },
  technicalDetails: {
    carpet_area: '',
    plinth_area: '',
    built_up_area: '',
    super_built_up_area: '',
    slab_area: '',
    total_built_up_area: '',
    plot_area: '',
    floor_area_ratio: '',
    ground_coverage: '',
    setback_front: '',
    setback_back: '',
    setback_left: '',
    setback_right: '',
    foundation_type: '',
    wall_thickness: '',
    plinth_height: '',
    ceiling_height: '',
    slab_thickness: '',
    beam_size: '',
    column_size: '',
    electrical_wiring_done: true,
    plumbing_work_done: true,
    ac_points_provided: true,
    fire_fighting_system: true,
    number_of_electrical_points: '',
    number_of_water_outlets: '',
    technical_assessment: '',
    landMeasurements: {
      shape: 'Regular',
      north: { actual: '', document: '', plan: '', match: false },
      south: { actual: '', document: '', plan: '', match: false },
      east: { actual: '', document: '', plan: '', match: false },
      west: { actual: '', document: '', plan: '', match: false },
    },
    buildingMeasurements: {
      shape: 'Regular',
      north: { actual: '', document: '', plan: '', match: false },
      south: { actual: '', document: '', plan: '', match: false },
      east: { actual: '', document: '', plan: '', match: false },
      west: { actual: '', document: '', plan: '', match: false },
    },
  },
  finalValuation: {
    property_type: '',
    property_use: '',
    valuation_purpose: '',
    valuation_date: '',
    final_market_value: '',
    final_guideline_value: '',
    distress_value: '',
    forced_sale_value: '',
    replacement_cost: '',
    depreciated_cost: '',
    certificate_issued: true,
    report_certified: true,
    photographs_attached: true,
    documents_verified: true,
    valuer_name: '',
    valuer_license_no: '',
    report_date: '',
    valuer_remarks: '',
  },
  locationDetails: {
    latitude: '',
    longitude: '',
    manual_latitude: '',
    manual_longitude: '',
  },
  propertyCharacteristics: {
    joint_wall_direction: '',
    joint_slab_direction: '',
    fsi: '',
    nearest_railway_station_km: '',
    nearest_bus_station_km: '',
    nearest_connecting_road_km: '',
    valuation_methodology: '',
    risk_of_demolition: '',
    distance_from_city_centre_km: '',
    distance_from_branch_km: '',
    negative_area_as_per_local: false,
    development_of_vicinity: '',
    habitation_around_property_percent: '',
    availability_of_local_transport: '',
    level_of_land: '',
    setback_deviation_percent: '',
    vertical_deviation: '',
    structure_confirming_to_safety: true,
    others_remarks: '',
  },
  ndmaParameters: {
    nature_of_building: '',
    shape_of_building: '',
    concrete_grade: '',
    roof_type: '',
    soil_strata: '',
    seismic_zone: '',
  },
  landExtentValuations: [
    { basis_of_valuation: 'as_per_documents', land_extent_sqft: '', cost_per_sqft: '', total_value: '' },
    { basis_of_valuation: 'as_per_actual', land_extent_sqft: '', cost_per_sqft: '', total_value: '' },
    { basis_of_valuation: 'as_per_plan', land_extent_sqft: '', cost_per_sqft: '', total_value: '' },
    { basis_of_valuation: 'final_selected', land_extent_sqft: '', cost_per_sqft: '', total_value: '' },
  ],
  structureValuations: [
    { floor_details: 'carpet_area', area_sqft: '', recommendation_of_funding: '', cost_per_sqft: '', total_value: '' },
    { floor_details: 'plinth_area', area_sqft: '', recommendation_of_funding: '', cost_per_sqft: '', total_value: '' },
    { floor_details: 'built_up_area', area_sqft: '', recommendation_of_funding: '', cost_per_sqft: '', total_value: '' },
    { floor_details: 'super_built', area_sqft: '', recommendation_of_funding: '', cost_per_sqft: '', total_value: '' },
    { floor_details: 'slab_area', area_sqft: '', recommendation_of_funding: '', cost_per_sqft: '', total_value: '' },
  ],
  structure_valuation_basis: 'as_per_actual',
  amenityValuations: [
    { amenity_name: '', amenity_value: '' },
  ],
  photos: [
    {
      id: 1,
      file: null,
      preview: null,
      description: '',
      latitude: '',
      longitude: '',
      locality: '',
      region: '',
      bearing_degrees: '',
      bearing_direction: '',
      captured_at: '',
    },
  ],
  signatures: {
    signature_inspector: '',
    signature_valuer: '',
    signature_engineer: '',
    signature_institution: '',
  },
};

const emptyPhoto = () => ({
  id: Date.now(),
  file: null,
  preview: null,
  description: '',
  latitude: '',
  longitude: '',
  locality: '',
  region: '',
  bearing_degrees: '',
  bearing_direction: '',
  captured_at: '',
});

/** One-click sample data for testing — fills every wired field and table row. */
export const getSampleFormData = () => {
  const today = new Date().toISOString().slice(0, 10);
  const inspectionDate = new Date(Date.now() - 5 * 86400000).toISOString().slice(0, 10);

  return {
    institutionDetails: {
      bank_name: 'HDFC Bank',
      branch_name: 'Chennai Main Branch',
      vendor_engineer_institution_name: 'KGN Associates',
      vendor_contact_number: '9876543210',
      site_engineer_name: 'Rajesh Kumar',
      site_engineer_contact_number: '9876543211',
      loan_application_id: 'LA2024001234',
      product_loan_type: 'Home Loan',
      applicant_name: 'John Doe',
      applicant_contact_number: '9876543212',
      property_owner_name: 'John Doe',
      property_owner_contact_number: '9876543212',
      person_met_at_site: 'Jane Smith',
      person_met_contact_number: '9876543213',
      relationship_with_applicant: 'Spouse',
      property_holding_type: 'freehold',
      property_type: 'residential_house',
      property_sub_type: 'Apartment',
      date_of_inspection: inspectionDate,
      date_of_report: today,
      document_number: 'DOC-2024-8891',
      execution_date: '2024-01-15',
      expiry_date: '2034-01-15',
      in_favour_of: 'John Doe',
      approval_authority: 'Municipal Corporation / CMDA',
    },
    verifiedDocuments: [
      {
        type_of_document: 'Sale Deed',
        document_number: 'DOC-2024-8891',
        execution_date: '2024-01-15',
        expiry_date: '2034-01-15',
        in_favour_of: 'John Doe',
        approval_authority: 'Municipal Corporation / CMDA',
      },
    ],
    propertyIdentification: {
      address_as_per_documents: '123 Main Street, T. Nagar, Chennai, Tamil Nadu',
      address_as_per_actual_site: '123 Main Street, T. Nagar, Chennai, Tamil Nadu',
      address_as_per_plan: '123 Main Street, T. Nagar, Chennai, Tamil Nadu',
      survey_number: '123/456',
      plot_no_flat_no: 'A-101',
      lpm_approval_no: 'LPM-2024-789',
      door_no: '123',
      assessment_no: 'AS-2024-456',
      landmark: 'Near Central Station',
      locality_name: 'T. Nagar',
      grama_polam: 'GP-123',
      jurisdiction: 'Chennai Corporation',
      taluka: 'Chennai',
      mandal: 'Chennai South',
      district: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600017',
      layout_plan_available: true,
      construction_plan_available: true,
      plan_validity: true,
      approving_authority: 'CMDA',
      approved_usage: 'Residential',
    },
    scheduleDetails: {
      east_boundary_docs: '30 ft',
      west_boundary_docs: '30 ft',
      north_boundary_docs: '40 ft',
      south_boundary_docs: '40 ft',
      east_boundary_actual: '30 ft',
      west_boundary_actual: '30 ft',
      north_boundary_actual: '40 ft',
      south_boundary_actual: '40 ft',
      east_boundary_plan: '30 ft',
      west_boundary_plan: '30 ft',
      north_boundary_plan: '40 ft',
      south_boundary_plan: '40 ft',
      east_boundary_status: 'Matched',
      west_boundary_status: 'Matched',
      north_boundary_status: 'Matched',
      south_boundary_status: 'Matched',
      docs_title: 'Sale Deed No. 4521/2018',
      actual_title: 'Site Physical Inspection',
      plan_title: 'Sanctioned Layout Plan',
      extra_boundaries: { docs: [], actual: [], plan: [] },
      property_identification_status: 'Identified',
      construction_type: 'rcc',
      roof_type: 'flat',
      flooring_type: 'marble',
      stair_type: 'RCC',
      no_of_floors_approved: '5',
      no_of_floors_existing: '4',
      construction_quality: 'Good',
      maintenance_of_property: 'Good',
      occupancy_status: 'occupied',
      occupant_details: 'Owner occupied',
      actual_usage_of_property: 'residential',
      approved_usage_of_property: 'residential',
      class_of_locality: 'Prime',
      other_class_of_locality: '',
      number_of_floors: '4',
    },
    infrastructureDetails: {
      land_locked: false,
      land_locked_description: 'Corner plot with road access on two sides',
      number_of_roads: '2',
      road_direction: 'north',
      approach_road_type: 'black_top_road',
      other_approach_road_type: '',
      type_of_access: 'public',
      road_width_ft: '30',
      road_direction_2: 'east',
      approach_road_type_2: 'cement_concrete_road',
      other_approach_road_type_2: '',
      type_of_access_2: 'public',
      road_width_ft_2: '40',
      electricity: true,
      water: true,
      drainage_connection: true,
      number_of_lifts: '2',
    },
    technicalDetails: {
      total_built_up_area: '2400',
      carpet_area: '2000',
      plot_area: '1200',
      floor_area_ratio: '2',
      ground_coverage: '60',
      setback_front: '10',
      setback_back: '10',
      setback_left: '5',
      setback_right: '5',
      foundation_type: 'raft',
      wall_thickness: '9-inch',
      plinth_height: '4',
      ceiling_height: '10',
      slab_thickness: '6',
      beam_size: '9x18',
      column_size: '12x18',
      electrical_wiring_done: true,
      plumbing_work_done: true,
      ac_points_provided: true,
      fire_fighting_system: true,
      number_of_electrical_points: '20',
      number_of_water_outlets: '5',
      technical_assessment: 'Construction quality is good with proper structural integrity.',
    },
    finalValuation: {
      property_type: 'Residential Apartment',
      property_use: 'Self Occupied',
      valuation_purpose: 'Home Loan',
      valuation_date: today,
      final_market_value: '50000000',
      final_guideline_value: '45000000',
      distress_value: '35000000',
      forced_sale_value: '38000000',
      replacement_cost: '55000000',
      depreciated_cost: '48000000',
      certificate_issued: true,
      report_certified: true,
      photographs_attached: true,
      documents_verified: true,
      valuer_name: 'Er. R. Kumar',
      report_date: today,
      valuer_remarks: 'Property is in good condition with proper documentation.',
    },
    locationDetails: {
      latitude: '13.0827',
      longitude: '80.2707',
      manual_latitude: '13.0827',
      manual_longitude: '80.2707',
    },
    propertyCharacteristics: {
      joint_wall_direction: 'East',
      joint_slab_direction: 'North',
      fsi: '2',
      nearest_railway_station_km: '5',
      nearest_bus_station_km: '2',
      nearest_connecting_road_km: '1',
      valuation_methodology: 'market',
      risk_of_demolition: 'low',
      distance_from_city_centre_km: '8',
      distance_from_branch_km: '3',
      negative_area_as_per_local: false,
      development_of_vicinity: 'developed',
      habitation_around_property_percent: '85',
      availability_of_local_transport: 'good',
      level_of_land: 'flat',
      setback_deviation_percent: '5',
      vertical_deviation: 'None',
      structure_confirming_to_safety: true,
      others_remarks: 'Property is well maintained with no major issues.',
    },
    ndmaParameters: {
      nature_of_building: 'Residential Apartment',
      shape_of_building: 'regular',
      concrete_grade: 'M-25',
      roof_type: 'flat',
      soil_strata: 'hard',
      seismic_zone: 'zone3',
    },
    landExtentValuations: [
      { basis_of_valuation: 'as_per_documents', land_extent_sqft: '1200', cost_per_sqft: '2000', total_value: '2400000' },
      { basis_of_valuation: 'as_per_actual', land_extent_sqft: '1100', cost_per_sqft: '2000', total_value: '2200000' },
      { basis_of_valuation: 'as_per_plan', land_extent_sqft: '1300', cost_per_sqft: '2000', total_value: '2600000' },
      { basis_of_valuation: 'final_selected', land_extent_sqft: '1200', cost_per_sqft: '2000', total_value: '2400000' },
    ],
    structureValuations: [
      { floor_details: 'carpet_area', area_sqft: '900', recommendation_of_funding: '80%', cost_per_sqft: '1500', total_value: '1080000' },
      { floor_details: 'plinth_area', area_sqft: '1000', recommendation_of_funding: '80%', cost_per_sqft: '1500', total_value: '1200000' },
      { floor_details: 'built_up_area', area_sqft: '1200', recommendation_of_funding: '85%', cost_per_sqft: '1500', total_value: '1530000' },
      { floor_details: 'super_built', area_sqft: '1400', recommendation_of_funding: '90%', cost_per_sqft: '1500', total_value: '1890000' },
      { floor_details: 'slab_area', area_sqft: '1100', recommendation_of_funding: '80%', cost_per_sqft: '1500', total_value: '1320000' },
    ],
    structure_valuation_basis: 'as_per_actual',
    amenityValuations: [
      { amenity_name: 'Car Parking', amenity_value: '200000' },
      { amenity_name: 'Lift', amenity_value: '150000' },
    ],
    photos: [emptyPhoto()],
    signatures: {
      signature_inspector: '',
      signature_valuer: '',
      signature_engineer: '',
      signature_institution: '',
    },
  };
};

export const sanitizePayload = (data) => {
  const cleaned = { ...data };
  delete cleaned.id;
  delete cleaned.valuation;
  delete cleaned.created_at;
  delete cleaned.updated_at;
  delete cleaned.verified_documents;
  return cleaned;
};

export const parseNumber = (value) => {
  if (value === '' || value === null || value === undefined) return null;
  const num = Number(String(value).replace(/[₹,\s]/g, ''));
  return Number.isNaN(num) ? null : num;
};

/** Round GPS coords to 8 decimal places (matches DB field limits). */
export const roundCoord = (value, decimals = 8) => {
  if (value === '' || value === null || value === undefined) return '';
  const num = Number(value);
  if (Number.isNaN(num)) return '';
  return num.toFixed(decimals);
};
