import mongoose from 'mongoose';

const VerifiedDocumentSchema = new mongoose.Schema({
  document_type: { type: String, default: '' },
  document_number: { type: String, default: '' },
  execution_date: { type: String, default: '' },
  expiry_date: { type: String, default: '' },
  in_favour_of: { type: String, default: '' },
  approval_authority: { type: String, default: '' },
}, { _id: true });

const LandExtentValuationSchema = new mongoose.Schema({
  basis_of_valuation: { type: String, default: 'as_per_documents' },
  land_extent_sqft: { type: Number, default: 0 },
  cost_per_sqft: { type: Number, default: 0 },
  total_value: { type: Number, default: 0 },
}, { _id: true });

const StructureValuationSchema = new mongoose.Schema({
  floor_details: { type: String, default: 'plinth_area' },
  area_sqft: { type: Number, default: 0 },
  recommendation_of_funding: { type: String, default: '' },
  cost_per_sqft: { type: Number, default: 0 },
  total_value: { type: Number, default: 0 },
}, { _id: true });

const AmenityValuationSchema = new mongoose.Schema({
  amenity_name: { type: String, default: '' },
  amenity_value: { type: Number, default: 0 },
}, { _id: true });

const PropertyPhotoSchema = new mongoose.Schema({
  photo: { type: String, default: '' }, // base64 or URL
  description: { type: String, default: '' },
  latitude: { type: Number, default: null },
  longitude: { type: Number, default: null },
  locality: { type: String, default: '' },
  region: { type: String, default: '' },
  bearing_degrees: { type: String, default: '' },
  bearing_direction: { type: String, default: '' },
  captured_at: { type: String, default: '' },
  uploaded_at: { type: Date, default: Date.now },
}, { _id: true });

const ValuationReportSchema = new mongoose.Schema(
  {
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },
    status: {
      type: String,
      enum: ['draft', 'in_progress', 'completed'],
      default: 'draft',
    },
    report_number: {
      type: String,
      default: () => `KGN-${Date.now().toString().slice(-6)}`,
    },

    institutionDetails: {
      bank_name: { type: String, default: '' },
      branch_name: { type: String, default: '' },
      vendor_engineer_institution_name: { type: String, default: '' },
      vendor_contact_number: { type: String, default: '' },
      site_engineer_name: { type: String, default: '' },
      site_engineer_contact_number: { type: String, default: '' },
      loan_application_id: { type: String, default: '' },
      product_loan_type: { type: String, default: '' },
      applicant_name: { type: String, default: '' },
      applicant_contact_number: { type: String, default: '' },
      property_owner_name: { type: String, default: '' },
      property_owner_contact_number: { type: String, default: '' },
      person_met_at_site: { type: String, default: '' },
      person_met_contact_number: { type: String, default: '' },
      relationship_with_applicant: { type: String, default: '' },
      property_holding_type: { type: String, default: 'freehold' },
      property_type: { type: String, default: 'open_plot' },
      property_sub_type: { type: String, default: '' },
      date_of_inspection: { type: String, default: '' },
      date_of_report: { type: String, default: '' },
    },

    verifiedDocuments: [VerifiedDocumentSchema],

    propertyIdentification: {
      address_as_per_documents: { type: String, default: '' },
      address_as_per_actual_site: { type: String, default: '' },
      address_as_per_plan: { type: String, default: '' },
      survey_number: { type: String, default: '' },
      plot_no_flat_no: { type: String, default: '' },
      lpm_approval_no: { type: String, default: '' },
      door_no: { type: String, default: '' },
      assessment_no: { type: String, default: '' },
      landmark: { type: String, default: '' },
      locality_name: { type: String, default: '' },
      grama_polam: { type: String, default: '' },
      jurisdiction: { type: String, default: '' },
      taluka: { type: String, default: '' },
      mandal: { type: String, default: '' },
      district: { type: String, default: '' },
      state: { type: String, default: '' },
      pincode: { type: String, default: '' },
      layout_plan_available: { type: Boolean, default: true },
      construction_plan_available: { type: Boolean, default: true },
      plan_validity: { type: Boolean, default: true },
      approving_authority: { type: String, default: '' },
      approved_usage: { type: String, default: '' },
    },

    scheduleDetails: {
      east_boundary_docs: { type: String, default: '' },
      west_boundary_docs: { type: String, default: '' },
      north_boundary_docs: { type: String, default: '' },
      south_boundary_docs: { type: String, default: '' },
      east_boundary_actual: { type: String, default: '' },
      west_boundary_actual: { type: String, default: '' },
      north_boundary_actual: { type: String, default: '' },
      south_boundary_actual: { type: String, default: '' },
      east_boundary_plan: { type: String, default: '' },
      west_boundary_plan: { type: String, default: '' },
      north_boundary_plan: { type: String, default: '' },
      south_boundary_plan: { type: String, default: '' },
      east_boundary_status: { type: String, default: '' },
      west_boundary_status: { type: String, default: '' },
      north_boundary_status: { type: String, default: '' },
      south_boundary_status: { type: String, default: '' },
      property_identification_status: { type: String, default: '' },
      construction_type: { type: String, default: '' },
      other_construction_type: { type: String, default: '' },
      roof_type: { type: String, default: '' },
      other_roof_type: { type: String, default: '' },
      flooring_type: { type: String, default: '' },
      other_flooring_type: { type: String, default: '' },
      stair_type: { type: String, default: '' },
      other_stair_type: { type: String, default: '' },
      no_of_floors_approved: { type: mongoose.Schema.Types.Mixed, default: '' },
      no_of_floors_existing: { type: mongoose.Schema.Types.Mixed, default: '' },
      construction_quality: { type: String, default: '' },
      maintenance_of_property: { type: String, default: '' },
      occupancy_status: { type: String, default: 'occupied' },
      occupant_details: { type: String, default: '' },
      actual_usage_of_property: { type: String, default: 'residential' },
      approved_usage_of_property: { type: String, default: 'residential' },
      class_of_locality: { type: String, default: 'good' },
      number_of_floors: { type: mongoose.Schema.Types.Mixed, default: '' },
    },

    infrastructureDetails: {
      land_locked: { type: Boolean, default: false },
      land_locked_description: { type: String, default: '' },
      number_of_roads: { type: mongoose.Schema.Types.Mixed, default: 1 },
      road_direction: { type: String, default: 'north' },
      approach_road_type: { type: String, default: '' },
      other_approach_road_type: { type: String, default: '' },
      type_of_access: { type: String, default: 'public' },
      road_width_ft: { type: mongoose.Schema.Types.Mixed, default: 30 },
      electricity: { type: Boolean, default: true },
      water: { type: Boolean, default: true },
      drainage_connection: { type: Boolean, default: true },
      number_of_lifts: { type: mongoose.Schema.Types.Mixed, default: 0 },
      roads_details: { type: mongoose.Schema.Types.Mixed, default: [] },
    },

    technicalDetails: {
      total_built_up_area: { type: Number, default: 0 },
      carpet_area: { type: Number, default: 0 },
      plot_area: { type: Number, default: 0 },
      floor_area_ratio: { type: Number, default: 0 },
      ground_coverage: { type: Number, default: 0 },
      setback_front: { type: Number, default: 0 },
      setback_back: { type: Number, default: 0 },
      setback_left: { type: Number, default: 0 },
      setback_right: { type: Number, default: 0 },
      foundation_type: { type: String, default: 'shallow' },
      wall_thickness: { type: String, default: '9-inch' },
      plinth_height: { type: Number, default: 0 },
      ceiling_height: { type: Number, default: 10 },
      slab_thickness: { type: Number, default: 5 },
      beam_size: { type: String, default: '' },
      column_size: { type: String, default: '' },
      electrical_wiring_done: { type: Boolean, default: true },
      plumbing_work_done: { type: Boolean, default: true },
      ac_points_provided: { type: Boolean, default: true },
      fire_fighting_system: { type: Boolean, default: false },
      number_of_electrical_points: { type: Number, default: 0 },
      number_of_water_outlets: { type: Number, default: 0 },
      technical_assessment: { type: String, default: '' },
    },

    landExtentValuations: [LandExtentValuationSchema],
    structureValuations: [StructureValuationSchema],
    amenityValuations: [AmenityValuationSchema],

    finalValuation: {
      property_type: { type: String, default: '' },
      property_use: { type: String, default: '' },
      valuation_purpose: { type: String, default: '' },
      valuation_date: { type: String, default: '' },
      final_market_value: { type: Number, default: 0 },
      final_guideline_value: { type: Number, default: 0 },
      distress_value: { type: Number, default: 0 },
      forced_sale_value: { type: Number, default: 0 },
      replacement_cost: { type: Number, default: 0 },
      depreciated_cost: { type: Number, default: 0 },
      certificate_issued: { type: Boolean, default: true },
      report_certified: { type: Boolean, default: true },
      photographs_attached: { type: Boolean, default: true },
      documents_verified: { type: Boolean, default: true },
      valuer_name: { type: String, default: 'Er. K. G. N. Associates' },
      valuer_license_no: { type: String, default: '' },
      report_date: { type: String, default: '' },
      valuer_remarks: { type: String, default: '' },
    },

    locationDetails: {
      latitude: { type: Number, default: null },
      longitude: { type: Number, default: null },
      manual_latitude: { type: Number, default: null },
      manual_longitude: { type: Number, default: null },
    },

    propertyCharacteristics: {
      joint_wall_direction: { type: String, default: '' },
      joint_slab_direction: { type: String, default: '' },
      fsi: { type: Number, default: 0 },
      nearest_railway_station_km: { type: Number, default: 0 },
      nearest_bus_station_km: { type: Number, default: 0 },
      nearest_connecting_road_km: { type: Number, default: 0 },
      valuation_methodology: { type: String, default: 'market' },
      risk_of_demolition: { type: String, default: 'low' },
      distance_from_city_centre_km: { type: Number, default: 0 },
      distance_from_branch_km: { type: Number, default: 0 },
      negative_area_as_per_local: { type: Boolean, default: false },
      development_of_vicinity: { type: String, default: 'developed' },
      habitation_around_property_percent: { type: Number, default: 80 },
      availability_of_local_transport: { type: String, default: 'good' },
      level_of_land: { type: String, default: 'flat' },
      setback_deviation_percent: { type: Number, default: 0 },
      vertical_deviation: { type: String, default: '' },
      structure_confirming_to_safety: { type: Boolean, default: true },
      others_remarks: { type: String, default: '' },
    },

    ndmaParameters: {
      nature_of_building: { type: String, default: '' },
      shape_of_building: { type: String, default: 'regular' },
      concrete_grade: { type: String, default: 'M20' },
      roof_type: { type: String, default: 'flat' },
      soil_strata: { type: String, default: 'medium' },
      seismic_zone: { type: String, default: 'zone3' },
    },

    photos: [PropertyPhotoSchema],
  },
  {
    timestamps: true,
  }
);

export default mongoose.models.ValuationReport || mongoose.model('ValuationReport', ValuationReportSchema);
